--- 
- hosts: all
  become: true
  
  tasks: 
    - name: installing multi sw
      yum: name="{{item}}" state=installed
      with_items:
            - httpd
            - mysql
            - git
            - tree
            - docker
            - java  
