--- 
- name: my second condition playbook
  hosts: all
  become: true
  user: ansible
  connection: ssh
  
  tasks:
    - name: install htppd package
      yum: 
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
         name: httpd
         state: started
      when: ansible_os_family == "RedHat"

    - name: install apache2 package
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service: 
         name: apache2
         state: started
      when: ansible_os_family == "Debian"
    
    - name: copy index.html
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        owner: hari
        mode: 0777     

