--- # create user playbook
- name: my test file
  hosts: all
  become: yes
  user: ansible
  connection: ssh

  tasks:
    - name: creating filen
      file: 
        path: /home/ansible/projectfile 
        state: touch  
