--- # procedure for jenkins 
- name: install java and jenkins
  hosts: all
  become: yes
  user: ansible
  connection: ssh
  
  tasks:

    - name: installing java software
      yum:
        name: java
        state: installed
    
    - name: install wget command
      yum:
        name: wget
        state: installed

    - name: dowload jenkins sw
      get_url:
          url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
          dest: /etc/yum.repos.d/jenkins.repo

    - name: download jenkins key          
      rpm_key:
         state: present 
         key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: nstalling jenkins sw
      yum:
        name: jenkins
        state: installed

    - name: start jenkins services
      service: 
          name: jenkins
          state: enabled
          enable: yes      
          
