--- # my target section playbook
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: installing httpd sw on webservers group in ips2
      action: yum name=httpd state=installed
    
